# 2024 © Idan Hazay

from enum import Enum


class Errors(Enum):
    GENERAL = f"ERRR|001|General error"
    UNKNOWN = f"ERRR|002|Code not supported"
    LOGIN_DETAILS = f"ERRR|003|Please check your password and email/username and try again."
    USER_REGISTERED = f"ERRR|004|Username already registered"
    EMAIL_REGISTERED = f"ERRR|005|Email address already registered"
    EMAIL_NOT_REGISTERED = f"ERRR|006|Email is not registered"
    NOT_MATCHING_CODE = f"ERRR|007|Code not matching try again"
    CODE_EXPIRED = f"ERRR|008|Code has expired"
    NOT_VERIFIED = f"ERRR|009|User not verified"
    ALREADY_VERIFIED = f"ERRR|010|Already verified"
    FILE_UPLOAD = f"ERRR|011|File didnt upload correctly"
    NO_DELETE_PERMS = f"ERRR|012|Can't delete this user"
    INVALID_DIRECTORY = f"ERRR|013|Invalid directory"
    FILE_NOT_FOUND = f"ERRR|014|File not found"
    FILE_DOWNLOAD = f"ERRR|015|File didnt download correctly"
    FOLDER_EXISTS = f"ERRR|016|This folder already exists"
    EXISTS = f"ERRR|017|File/Folder with same name already exists"
    SAME_LEVEL = f"ERRR|018|Already at this subscription level"
    INVALID_LEVEL = f"ERRR|019|Invalid subscription level"
    MAX_STORAGE = f"ERRR|019|Max storage reached, try upgrading your subscription"
    SIZE_LIMIT = f"ERRR|020|File exceeded max size of"
    FILE_EXISTS = f"ERRR|021|A file with that name already exists"
    PREVIEW_SIZE = f"ERRR|022|File exceeds max preview size of 10 MB"
    NOT_LOGGED = f"ERRR|023|Can't upload files here"
    INVALID_COOKIE = f"ERRR|024|Cookie is invalid"
    EXPIRED_COOKIE = f"ERRR|025|Cookie is expired"
    NO_PERMS = f"ERRR|026|You don't have the permission to perform this action"
    USER_NOT_FOUND = f"ERRR|027|User with this username/email was not found"
    SELF_SHARE = f"ERRR|028|You cannot share with yourself"
    OWNER_SHARE = f"ERRR|029|You cannot share with owner"
    IN_USE = f"ERRR|030|File is currently in use"
