
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\idanh\Downloads\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1200x675")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 675,
    width = 1200,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1200.0,
    675.0,
    fill="#241717",
    outline="")

canvas.create_text(
    404.0,
    77.0,
    anchor="nw",
    text="Welcome To IdanCloud",
    fill="#FFFFFF",
    font=("InriaSans Regular", 40 * -1)
)

canvas.create_rectangle(
    403.0,
    149.00000009841804,
    794.9999999361935,
    151.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    496.0,
    391.0,
    703.0,
    442.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    548.0,
    396.0,
    anchor="nw",
    text="Signup",
    fill="#000000",
    font=("InriaSans Regular", 35 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=495.0,
    y=259.0,
    width=207.0,
    height=51.0
)
window.resizable(False, False)
window.mainloop()
