
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\idanh\Downloads\build\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1200x675")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 675,
    width = 1200,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1200.0,
    675.0,
    fill="#241717",
    outline="")

canvas.create_text(
    552.0,
    97.0,
    anchor="nw",
    text="Login",
    fill="#FFFFFF",
    font=("InriaSans Regular", 40 * -1)
)

canvas.create_rectangle(
    551.0,
    170.0,
    648.0,
    171.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    519.0,
    242.0,
    anchor="nw",
    text="Email/Username:",
    fill="#FFFFFF",
    font=("InriaSans Regular", 22 * -1)
)

canvas.create_text(
    552.0,
    390.0,
    anchor="nw",
    text="Password:",
    fill="#FFFFFF",
    font=("InriaSans Regular", 22 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    599.5,
    299.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=474.0,
    y=278.0,
    width=251.0,
    height=40.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    599.5,
    447.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=474.0,
    y=426.0,
    width=251.0,
    height=40.0
)
def on_submit():
    email_or_username = entry_1.get()
    password = entry_2.get()
    # Process the email/username and password
    print("Email/Username:", email_or_username)
    print("Password:", password)

submit_image = PhotoImage(
    file=relative_to_assets("button_1.png"))
submit = Button(
    image=submit_image,
    borderwidth=0,
    highlightthickness=0,
    command=on_submit,
    relief="flat"
)
submit.place(
    x=507.0,
    y=539.0,
    width=185.0,
    height=48.0
)


window.resizable(False, False)
window.mainloop()
